version: "3.9"
services:
  backend:
    build: ./backend
    container_name: fastapi_backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./generated_outputs:/app/generated_outputs

  frontend:
    build: ./frontend
    container_name: streamlit_frontend
    ports:
      - "8501:8501"
    volumes:
      - ./frontend:/app
      - ./generated_outputs:/app/generated_outputs
    depends_on:
      - backend
